server:
  port: 4112
spring:
  datasource:
    url: jdbc:h2:mem:desafioibk
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect